package atscale.biconnector.utils;

import java.util.List;

public class Constants {
    // Parameters
    public static final String SERVER_URI = "server_uri";

    public static final String BEFORE_QUERY =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                    "<Envelope xmlns=\"http://schemas.xmlsoap.org/soap/envelope/\">\n" +
                    "  <Body>\n" +
                    "    <Execute xmlns=\"urn:schemas-microsoft-com:xml-analysis\">\n" +
                    "      <Command>\n" +
                    "        <Statement>";
    public static final String AFTER_QUERY =
            "</Statement>\n" +
                    "      </Command>\n" +
                    "      <Properties>\n" +
                    "        <PropertyList>\n" +
                    "          <DbpropMsmdSubqueries>2</DbpropMsmdSubqueries>\n" +
                    "          <LocaleIdentifier>1033</LocaleIdentifier>\n" +
                    "          <Format>Tabular</Format>\n" +
                    "          <Content>SchemaData</Content>\n" +
                    "          <DbpropMsmdActivityID>2305a0fa-ddc8-499c-a815-04f2cfdb8ddc</DbpropMsmdActivityID>\n" +
                    "          <DbpropMsmdRequestID>1659f75d-0e2c-4864-a9b7-b61f92f9bb72</DbpropMsmdRequestID>\n" +
                    "        </PropertyList>\n" +
                    "      </Properties>\n" +
                    "    </Execute>\n" +
                    "  </Body>\n" +
                    "</Envelope>";
    public static final String AFTER_CATALOG_QUERY =
            "</Statement>\n" +
                    "      </Command>\n" +
                    "    </Execute>\n" +
                    "  </Body>\n" +
                    "</Envelope>";

    public static final String CATALOG_QUERY = "SELECT [CATALOG_NAME], [CATALOG_GUID], [ROLES], [DESCRIPTION], [DATE_MODIFIED], [COMPATIBILITY_LEVEL], [TYPE], [VERSION], [DATABASE_ID], [DATE_QUERIED], [CURRENTLY_USED] from $system.DBSCHEMA_CATALOGS";
    public static final String CATALOG_SELECTIVE_QUERY =
            "SELECT [CATALOG_NAME], [CATALOG_GUID], [ROLES], [DESCRIPTION], [DATE_MODIFIED], [COMPATIBILITY_LEVEL], [TYPE], [VERSION], [DATABASE_ID], [DATE_QUERIED], [CURRENTLY_USED] from $system.DBSCHEMA_CATALOGS WHERE CATALOG_NAME IN (%s)";
    public static final String DATASOURCE_QUERY = CATALOG_QUERY;

    // New cube columns in 2022.2 are [IS_DRILLTHROUGH_ENABLED] and [PREFERRED_QUERY_PATTERNS]
    public static final String CUBE_SELECTIVE_QUERY =
            "SELECT [CUBE_NAME], [CUBE_GUID], [CATALOG_NAME], [BASE_CUBE_NAME], [SCHEMA_NAME], [CUBE_TYPE], [CREATED_ON], [LAST_SCHEMA_UPDATE], [LAST_DATA_UPDATE], [DATA_UPDATED_BY], [DESCRIPTION], [CUBE_CAPTION], [CUBE_SOURCE], [IS_DRILLTHROUGH_ENABLED], [PREFERRED_QUERY_PATTERNS] from $system.MDSCHEMA_CUBES WHERE [CUBE_NAME] = '%s'";
    public static final String CUBE_NAME_SELECTIVE_QUERY =
            "SELECT [CUBE_NAME], [CUBE_GUID], [CATALOG_NAME], [BASE_CUBE_NAME], [SCHEMA_NAME], [CUBE_TYPE], [CREATED_ON], [LAST_SCHEMA_UPDATE], [LAST_DATA_UPDATE], [DATA_UPDATED_BY], [DESCRIPTION], [CUBE_CAPTION], [CUBE_SOURCE], [IS_DRILLTHROUGH_ENABLED], [PREFERRED_QUERY_PATTERNS] from $system.MDSCHEMA_CUBES WHERE [CUBE_NAME] = '%s'";
    public static final String CUBE_NAME_FROM_CATALOG_SELECTIVE_QUERY =
            "SELECT [CUBE_NAME], [CATALOG_NAME], [BASE_CUBE_NAME], [SCHEMA_NAME], [CUBE_TYPE], [CUBE_GUID], [CREATED_ON], [LAST_SCHEMA_UPDATE], [LAST_DATA_UPDATE], [DATA_UPDATED_BY], [DESCRIPTION], [CUBE_CAPTION], [CUBE_SOURCE], [IS_DRILLTHROUGH_ENABLED], [PREFERRED_QUERY_PATTERNS] from $system.MDSCHEMA_CUBES WHERE [CATALOG_NAME] = '%s'";
    public static final String LISTED_CUBE_QUERY =
            "SELECT [CUBE_NAME], [CATALOG_NAME], [BASE_CUBE_NAME], [SCHEMA_NAME], [CUBE_TYPE], [CUBE_GUID], [CREATED_ON], [LAST_SCHEMA_UPDATE], [LAST_DATA_UPDATE], [DATA_UPDATED_BY], [DESCRIPTION], [CUBE_CAPTION], [CUBE_SOURCE], [IS_DRILLTHROUGH_ENABLED], [PREFERRED_QUERY_PATTERNS] from $system.MDSCHEMA_CUBES";

    // Since AtScale objects belong to the Project, ignore AtScale's concept of a data source (DSV) and use the DBSCHEMA_CATALOGS query instead
    public static final String COLUMN_QUERY =
            "SELECT [CATALOG_NAME], [DATASET_NAME], [COLUMN_NAME], [DATA_TYPE], [EXPRESSION], [CONNECTION_ID] FROM $system.DBSCHEMA_COLUMNS";
    public static final String COLUMN_SELECTIVE_QUERY =
            "SELECT [CATALOG_NAME], [DATASET_NAME], [COLUMN_NAME], [DATA_TYPE], [EXPRESSION], [CONNECTION_ID] FROM $system.DBSCHEMA_COLUMNS WHERE [CATALOG_NAME] IN (%s)";


    // New dataset column in 2022.2 is [DATABASE]
    public static final String DATASET_QUERY =
            "SELECT [CATALOG_NAME], [CUBE_GUID], [DATASET_NAME], [DATABASE], [TABLE], [SCHEMA], [EXPRESSION], [CONNECTION_ID] FROM $system.DBSCHEMA_TABLES";
    public static final String DATASET_SELECTIVE_QUERY =
            "SELECT [CATALOG_NAME], [CUBE_GUID], [DATASET_NAME], [DATABASE], [TABLE], [SCHEMA], [EXPRESSION], [CONNECTION_ID] FROM $system.DBSCHEMA_TABLES WHERE [CATALOG_NAME] IN (%s)";

    public static final String DIMENSION_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_NAME], [DIMENSION_GUID], [DIMENSION_UNIQUE_NAME], [DIMENSION_CAPTION], [DIMENSION_ORDINAL], [DIMENSION_TYPE], [DIMENSION_CARDINALITY], [DEFAULT_HIERARCHY], [DESCRIPTION], [IS_VIRTUAL], [IS_READWRITE], [DIMENSION_UNIQUE_SETTINGS], [DIMENSION_MASTER_NAME], [DIMENSION_IS_VISIBLE] FROM $system.MDSCHEMA_DIMENSIONS WHERE [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]'";
    public static final String DIMENSION_SELECTIVE_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_NAME], [DIMENSION_GUID], [DIMENSION_UNIQUE_NAME], [DIMENSION_CAPTION], [DIMENSION_ORDINAL], [DIMENSION_TYPE], [DIMENSION_CARDINALITY], [DEFAULT_HIERARCHY], [DESCRIPTION], [IS_VIRTUAL], [IS_READWRITE], [DIMENSION_UNIQUE_SETTINGS], [DIMENSION_MASTER_NAME], [DIMENSION_IS_VISIBLE] FROM $system.MDSCHEMA_DIMENSIONS WHERE [CUBE_NAME] = '%s' AND [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]'";
    public static final String DIMENSION_ON_CATALOG_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_NAME], [DIMENSION_GUID], [DIMENSION_UNIQUE_NAME], [DIMENSION_CAPTION], [DIMENSION_ORDINAL], [DIMENSION_TYPE], [DIMENSION_CARDINALITY], [DEFAULT_HIERARCHY], [DESCRIPTION], [IS_VIRTUAL], [IS_READWRITE], [DIMENSION_UNIQUE_SETTINGS], [DIMENSION_MASTER_NAME], [DIMENSION_IS_VISIBLE] FROM $system.MDSCHEMA_DIMENSIONS WHERE [CATALOG_NAME] = '%s' AND [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]'";

    // New hierarchy columns in 2022.2: [DIMENSION_IS_SHARED], [HIERARCHY_IS_VISIBLE], [HIERARCHY_ORDINAL]
    public static final String HIERARCHY_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_UNIQUE_NAME], [HIERARCHY_NAME], [HIERARCHY_UNIQUE_NAME], [HIERARCHY_GUID], [HIERARCHY_CAPTION], [DIMENSION_TYPE], [HIERARCHY_CARDINALITY], [DEFAULT_MEMBER], [ALL_MEMBER], [DESCRIPTION], [STRUCTURE], [IS_VIRTUAL], [IS_READWRITE], [DIMENSION_UNIQUE_SETTINGS], [DIMENSION_MASTER_UNIQUE_NAME], [DIMENSION_IS_VISIBLE], [HIERARCHY_ORIGIN], [HIERARCHY_DISPLAY_FOLDER], [INSTANCE_SELECTION], [GROUPING_BEHAVIOR], [STRUCTURE_TYPE], [DIMENSION_IS_SHARED], [HIERARCHY_IS_VISIBLE], [HIERARCHY_ORDINAL] FROM $system.MDSCHEMA_HIERARCHIES WHERE [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]'";
    public static final String HIERARCHY_SELECTIVE_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_UNIQUE_NAME], [HIERARCHY_NAME], [HIERARCHY_UNIQUE_NAME], [HIERARCHY_GUID], [HIERARCHY_CAPTION], [DIMENSION_TYPE], [HIERARCHY_CARDINALITY], [DEFAULT_MEMBER], [ALL_MEMBER], [DESCRIPTION], [STRUCTURE], [IS_VIRTUAL], [IS_READWRITE], [DIMENSION_UNIQUE_SETTINGS], [DIMENSION_MASTER_UNIQUE_NAME], [DIMENSION_IS_VISIBLE], [HIERARCHY_ORIGIN], [HIERARCHY_DISPLAY_FOLDER], [INSTANCE_SELECTION], [GROUPING_BEHAVIOR], [STRUCTURE_TYPE], [DIMENSION_IS_SHARED], [HIERARCHY_IS_VISIBLE], [HIERARCHY_ORDINAL] FROM $system.MDSCHEMA_HIERARCHIES WHERE [CUBE_NAME] = '%s' AND [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]'";
    public static final String HIERARCHY_ON_CATALOG_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_UNIQUE_NAME], [HIERARCHY_NAME], [HIERARCHY_UNIQUE_NAME], [HIERARCHY_GUID], [HIERARCHY_CAPTION], [DIMENSION_TYPE], [HIERARCHY_CARDINALITY], [DEFAULT_MEMBER], [ALL_MEMBER], [DESCRIPTION], [STRUCTURE], [IS_VIRTUAL], [IS_READWRITE], [DIMENSION_UNIQUE_SETTINGS], [DIMENSION_MASTER_UNIQUE_NAME], [DIMENSION_IS_VISIBLE], [HIERARCHY_ORIGIN], [HIERARCHY_DISPLAY_FOLDER], [INSTANCE_SELECTION], [GROUPING_BEHAVIOR], [STRUCTURE_TYPE], [DIMENSION_IS_SHARED], [HIERARCHY_IS_VISIBLE], [HIERARCHY_ORDINAL] FROM $system.MDSCHEMA_HIERARCHIES WHERE [CATALOG_NAME] = '%s' AND [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]'";

    public static final String LEVEL_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_UNIQUE_NAME], [HIERARCHY_UNIQUE_NAME], [LEVEL_NAME], [LEVEL_UNIQUE_NAME], [LEVEL_GUID], [LEVEL_CAPTION], [LEVEL_NUMBER], [LEVEL_CARDINALITY], [LEVEL_TYPE], [DESCRIPTION], [CUSTOM_ROLLUP_SETTINGS], [LEVEL_UNIQUE_SETTINGS], [LEVEL_IS_VISIBLE], [LEVEL_ORDERING_PROPERTY], [LEVEL_DBTYPE], [LEVEL_MASTER_UNIQUE_NAME], [LEVEL_NAME_SQL_COLUMN_NAME], [LEVEL_KEY_SQL_COLUMN_NAME], [LEVEL_UNIQUE_NAME_SQL_COLUMN_NAME], [LEVEL_ATTRIBUTE_HIERARCHY_NAME], [LEVEL_KEY_CARDINALITY], [LEVEL_ORIGIN], [DATASET_NAME], [LEVEL_NAME_SQL_COLUMN_NAME], [LEVEL_KEY_SQL_COLUMN_NAME], [LEVEL_SORT_SQL_COLUMN_NAME], [LEVEL_DBTYPE_NAME_COLUMN], [LEVEL_DBTYPE_SORT_COLUMN], [IS_PRIMARY], [PARENT_LEVEL_ID] FROM $system.MDSCHEMA_LEVELS WHERE [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]' AND [LEVEL_NAME] &lt;&gt; '(All)'";
    public static final String LEVEL_SELECTIVE_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [DIMENSION_UNIQUE_NAME], [HIERARCHY_UNIQUE_NAME], [LEVEL_NAME], [LEVEL_UNIQUE_NAME], [LEVEL_GUID], [LEVEL_CAPTION], [LEVEL_NUMBER], [LEVEL_CARDINALITY], [LEVEL_TYPE], [DESCRIPTION], [CUSTOM_ROLLUP_SETTINGS], [LEVEL_UNIQUE_SETTINGS], [LEVEL_IS_VISIBLE], [LEVEL_ORDERING_PROPERTY], [LEVEL_DBTYPE], [LEVEL_MASTER_UNIQUE_NAME], [LEVEL_NAME_SQL_COLUMN_NAME], [LEVEL_KEY_SQL_COLUMN_NAME], [LEVEL_UNIQUE_NAME_SQL_COLUMN_NAME], [LEVEL_ATTRIBUTE_HIERARCHY_NAME], [LEVEL_KEY_CARDINALITY], [LEVEL_ORIGIN], [DATASET_NAME], [LEVEL_NAME_SQL_COLUMN_NAME], [LEVEL_KEY_SQL_COLUMN_NAME], [LEVEL_SORT_SQL_COLUMN_NAME], [LEVEL_DBTYPE_NAME_COLUMN], [LEVEL_DBTYPE_SORT_COLUMN], [IS_PRIMARY], [PARENT_LEVEL_ID] FROM $system.MDSCHEMA_LEVELS WHERE [CUBE_NAME] = '%s' AND [DIMENSION_UNIQUE_NAME] &lt;&gt; '[Measures]' AND [LEVEL_NAME] &lt;&gt; '(All)'";

    public static final String MEASUREGROUP_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [MEASUREGROUP_NAME], [MEASUREGROUP_CAPTION], [DESCRIPTION], [IS_WRITE_ENABLED] FROM $system.MDSCHEMA_MEASUREGROUPS";
    public static final String MEASUREGROUP_SELECTIVE_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [MEASUREGROUP_NAME], [MEASUREGROUP_CAPTION], [DESCRIPTION], [IS_WRITE_ENABLED] FROM $system.MDSCHEMA_MEASUREGROUPS WHERE [CUBE_NAME] = '%s'";

    // New columns in 2022.2: [IS_METRICAL_ATTRIBUTE], [PARENT_LEVEL_ID], [PARENT_LEVEL_NAME]
    public static final String MEASURE_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [MEASURE_NAME], [MEASURE_UNIQUE_NAME], [MEASURE_GUID], [MEASURE_CAPTION], [MEASURE_AGGREGATOR], [DATA_TYPE], [COLUMN_NAME], [COLUMN_DATA_TYPE], [NUMERIC_PRECISION], [NUMERIC_SCALE], [MEASURE_UNITS], [DESCRIPTION], [EXPRESSION], [MEASURE_IS_VISIBLE], [MEASURE_IS_VISIBLE], [MEASURE_NAME_SQL_COLUMN_NAME], [MEASURE_UNQUALIFIED_CAPTION], [MEASUREGROUP_NAME], [MEASURE_DISPLAY_FOLDER], [DEFAULT_FORMAT_STRING], [DATASET_NAME], [IS_METRICAL_ATTRIBUTE], [PARENT_LEVEL_ID], [PARENT_LEVEL_NAME] FROM $system.MDSCHEMA_MEASURES";
    public static final String MEASURE_SELECTIVE_QUERY =
            "SELECT [CATALOG_NAME], [SCHEMA_NAME], [CUBE_NAME], [CUBE_GUID], [MEASURE_NAME], [MEASURE_UNIQUE_NAME], [MEASURE_GUID], [MEASURE_CAPTION], [MEASURE_AGGREGATOR], [DATA_TYPE], [COLUMN_NAME], [COLUMN_DATA_TYPE], [NUMERIC_PRECISION], [NUMERIC_SCALE], [MEASURE_UNITS], [DESCRIPTION], [EXPRESSION], [MEASURE_IS_VISIBLE], [MEASURE_IS_VISIBLE], [MEASURE_NAME_SQL_COLUMN_NAME], [MEASURE_UNQUALIFIED_CAPTION], [MEASUREGROUP_NAME], [MEASURE_DISPLAY_FOLDER], [DEFAULT_FORMAT_STRING], [DATASET_NAME], [IS_METRICAL_ATTRIBUTE], [PARENT_LEVEL_ID], [PARENT_LEVEL_NAME] FROM $system.MDSCHEMA_MEASURES WHERE [CUBE_NAME] = '%s'";

    public static final String DEPENDENCIES_QUERY =
            "SELECT [DATABASE_NAME], [OBJECT_TYPE], [TABLE], [OBJECT], [EXPRESSION], [REFERENCED_OBJECT_TYPE], [REFERENCED_TABLE], [REFERENCED_OBJECT], [REFERENCED_EXPRESSION], [CATALOG_NAME], [CUBE_NAME] FROM $system.DISCOVER_CALC_DEPENDENCY";
    public static final String DEPENDENCIES_SELECTIVE_QUERY =
            "SELECT [DATABASE_NAME], [OBJECT_TYPE], [TABLE], [OBJECT], [EXPRESSION], [REFERENCED_OBJECT_TYPE], [REFERENCED_TABLE], [REFERENCED_OBJECT], [REFERENCED_EXPRESSION], [CATALOG_NAME], [CUBE_NAME] FROM $system.DISCOVER_CALC_DEPENDENCY WHERE [CUBE_NAME] = '%s'";


    // Field Name Constants
    public static final String CATALOG_NAME = "CATALOG_NAME";
    public static final String CUBE_NAME = "CUBE_NAME";
    public static final String SQL_QUERY = "SQL Query = ";
    public static final boolean PRINT_MSGS = false;
    public static final boolean PRINT_HEADERS = false;
    public static final List<String> FILTER = List.of("d_orderdate");
    // For testing, lists projects to include. If empty, no filter is applied
    public static List<String> PROJECTS_TO_FILTER = null;
    public static final boolean USE_TEST_FOLDERS_AND_USERS = false;
    public static final boolean IS_INCLUDE_FILTER = true; // Only used if useTestFoldersAndUsers is true
    public static final String SECONDARY_ATTRIBUTE = "Secondary Attribute";
    public static final String CATALOG_HTML_START = "<Catalog>";
    public static final String CATALOG_HTML_END_WITH_NEW_LINE = "</Catalog>\n";
    public static final String MEASURE = "Measure";
    public static final String SAMPLE_EXPRESSION = "Sample Expression";
    public static final String SAMPLE_VALUE_1 = "Sample Value 1";
    public static final String SAMPLE_VALUE_2 = "Sample Value 2";
    public static final String ADMINISTRATOR = "Administrator";


    // DATA TYPES
    public static final String INT = "Int";
    public static final String FLOAT = "Float";
    public static final String STRING = "String";

    private Constants() {
    }
}
